#!/bin/bash
#PBS -l select=1:ncpus=8:mem=256gb:ngpus=1
#PBS -l walltime=30:00:00
#PBS -N test_early_stop
#PBS -o /rds/general/user/eso18/home/mmvmvae/run_celeba/logs/early_stop.log
#PBS -e /rds/general/user/eso18/home/mmvmvae/run_celeba/logs/early_stop.err

eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate mvvae
cd mmvmvae

export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="${PYTHONPATH}:/rds/general/user/eso18/home/mmvmvae/"
dataset="CelebA"
model="jointprior"
seed=1
agg="avg"
alpha=0.95 
wandb_entity="eso18-imperial-college-london"
project_name="mvvae_celeba"
dir_experiments="/rds/general/user/eso18/home/mmvmvae"
dir_data_base="/rds/general/user/eso18/home/mmvmvae/data/CelebA"
wandb_logdir="${dir_experiments}/run_celeba/logs"
WD=$(pwd)
device="cuda"  # 'cuda' if you are useing a GPU
log_freq_downstream=50
log_freq_coherence=50
log_freq_lhood=50
log_freq_plotting=50
ld=256
beta=1      # KL weight (float)
aa=true     # alpha annealing steps (int)
a_w=0.5
ld=512 
lr=5e-4 
n_ep=400 
gamma=0.0001
cov_scalar=$(echo "1 - ($alpha^2)" | bc -l)

# run the classifier with a jointposterior
cd $WD
python main_mv_wsl.py \
    model=${model} \
    ++model.seed=${seed} \
    ++model.alpha_scalar=${alpha} \
    ++model.cov_scalar=${cov_scalar} \
    ++model.device=${device} \
    ++model.beta=${beta} \
    ++model.beta_annealing=false \
    ++model.early_stop=true \
    ++model.latent_dim=${ld} \
    ++model.lr=${lr} \
    ++model.epochs=${n_ep} \
    ++model.aggregation="${agg}" \
    dataset=${dataset} \
    ++dataset.modalities_order=${mod} \
    ++log.wandb_offline=false \
    ++log.downstream_logging_frequency=${log_freq_downstream} \
    ++log.coherence_logging_frequency=${log_freq_coherence} \
    ++log.likelihood_logging_frequency=${log_freq_lhood} \
    ++log.img_plotting_frequency=${log_freq_plotting} \
    ++log.wandb_offline=false \
    ++log.wandb_local_instance=true \
    ++log.wandb_entity=${wandb_entity} \
    ++log.wandb_group="full_runs" \
    ++log.wandb_project_name=${project_name} \
    ++log.dir_logs=${wandb_logdir}