#!/bin/bash
#PBS -l select=1:ncpus=8:mem=256gb:ngpus=1
#PBS -l walltime=10:00:00
#PBS -N joint_celeba
#PBS -o run_celeba/logs/classifier.log
#PBS -e run_celeba/logs/classifier.err

# set global variables
eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate mvvae
cd mmvmvae
export folder_path=${PWD}
export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="${PYTHONPATH}:${folder_path}"

# run the classifier
python run_celeba/main_train_clf_celeba.py \
  checkpoint_metric="val/loss/mean_ap"

