#!/bin/bash
#PBS -l select=1:ncpus=8:mem=50gb:ngpus=1
#PBS -l walltime=00:10:00
#PBS -N scMNC_no_cpu
#PBS -o run_scMNC/logs/run_scMNC_classifier.out
#PBS -e run_scMNC/logs/run_scMNC_classifier.err

eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate mvvae
cd mmvmvae
export folder_path=${PWD}
export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="${PYTHONPATH}:${folder_path}"

device="cuda"  # 'cuda' if you are using a GPU, 'cpu' otherwise

# run the classifier 
python run_scMNC/main_train_clf_scMNC.py ++model.device=${device}
