#!/bin/bash
#PBS -l select=1:ncpus=8:mem=250gb:ngpus=1
#PBS -l walltime=01:00:00
#PBS -N scMNC_classifier
#PBS -o /rds/general/user/eso18/home/mmvmvae/run_scMNC/logs/run_scMNC_classifier.out
#PBS -e /rds/general/user/eso18/home/mmvmvae/run_scMNC/logs/run_scMNC_classifier.err

eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate mvvae
cd mmvmvae

# wandb login $WANDB_API_KEY
export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="${PYTHONPATH}:/rds/general/user/eso18/home/mmvmvae/"

# run the classifier first
python run_scMNC/main_train_clf_scMNC.py 