#!/bin/bash
#PBS -l select=1:ncpus=8:mem=256gb:ngpus=1
#PBS -l walltime=00:10:00
#PBS -N test_log_path
#PBS -o run_scMNC/logs/test.log
#PBS -e run_scMNC/logs/test.err

eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate mvvae
cd mmvmvae

# define user specific variables
export folder_path=${PWD}
project_name="mvvae_scMNC" # project name in wandb

# Set environment variables
export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="${PYTHONPATH}:${folder_path}"
cd $(pwd)

# dataset specific variables
dataset="scMNC"

# model specific variables
model="jointprior"
alpha=0.95 # alpha value if using for jointprior
cov_scalar=$(echo "1 - ($alpha^2)" | bc -l)
agg="avg" # aggregation method for joint: 'mopoe', 'moe', 'avg'
aa=true  # whether to use alpha annealing for mixedprior

# architecture variables
ld=256 # latent dimension
hd=512 # hidden dimension of encoder/decoder 
batch_size=32 # batch size

# experimental running variables
seed=1
log_freq=1
wandb_logdir="${folder_path}/run_scMNC/logs"
device="cuda"  # 'cuda' if you are using a GPU

# training specific variables
beta_anneal=true # whether to use beta/kl annealing
lr=5e-4 # learning rate
n_ep=2500 # number of epochs
early_stop=true # whether to use early stopping

# run the classifier with a jointposterior
python run_experiment.py \
    model=${model} \
    ++model.seed=${seed} \
    ++model.alpha_scalar=${alpha} \
    ++model.cov_scalar=${cov_scalar} \
    ++model.device=${device} \
    ++model.beta=${beta} \
    ++model.batch_size=${batch_size} \
    ++model.beta_annealing=${beta_anneal} \
    ++model.early_stop=${early_stop} \
    ++model.latent_dim=${ld} \
    ++model.hidden_dim=${hd} \
    ++model.lr=${lr} \
    ++model.epochs=${n_ep} \
    ++model.aggregation="${agg}" \
    dataset=${dataset} \
    ++dataset.modalities_order=${mod} \
    ++log.downstream_logging_frequency=${log_freq} \
    ++log.coherence_logging_frequency=${log_freq} \
    ++log.likelihood_logging_frequency=${log_freq} \
    ++log.img_plotting_frequency=${log_freq} \
    ++log.val_freq=${log_freq} \
    ++log.wandb_offline=false \
    ++log.wandb_local_instance=true \
    ++log.wandb_group="full_runs" \
    ++log.wandb_project_name=${project_name} \
    ++log.dir_logs=${wandb_logdir}