#!/bin/bash
#PBS -l select=1:ncpus=8:mem=250gb:ngpus=1
#PBS -l walltime=20:00:00
#PBS -N poly_jp_all5
#PBS -o /rds/general/user/eso18/home/mmvmvae/run_PM/logs/run_example.out
#PBS -e /rds/general/user/eso18/home/mmvmvae/run_PM/logs/run_example.err

eval "$(~/anaconda3/bin/conda shell.bash hook)"
source activate mvvae
cd mmvmvae

# wandb login $WANDB_API_KEY
export CUDA_LAUNCH_BLOCKING=1
export TORCH_USE_CUDA_DSA=1
export HYDRA_FULL_ERROR=1
export PYTHONPATH="${PYTHONPATH}:/rds/general/user/eso18/home/mmvmvae/"

# run the classifier with a jointposterir
python main_mv_wsl.py dataset="PMtranslated75" model="jointprior"